from add import *
from address import *
from and_ast import *
from argdef import *
from array_ast import *
from assign import *
from attribute import *
from binop import *
from bitand import *
from bitor import *
from bitxor import *
from boolop import *
from call import *
from char import *
from compare import *
from div import *
from eq import *
from expr import *
from extern import *
from function import *
from geq import *
from gt import *
from if_ast import *
from int import *
from leq import *
from load import *
from lt import *
from mod import *
from mode import *
from more import *
from mul import *
from name import *
from neq import *
from num import *
from or_ast import *
from pass_ast import *
from pointer import *
from program import *
from return_ast import *
from store import *
from string_ast import *
from structdef import *
from struct_ast import *
from sub import *
from subscript import *
from syntaxtree import *
from type import *
from unpackref import *
from vardef import *
from void import *
from while_ast import *
